### ISSUE TITLE
Tin-terrain running from cmd

### ISSUE THREAD

**Issue by Tobias1234** [heremaps/tin-terrain#38]
Hi!
I want to run tin terrain directly from cmd without docker installation. Is it possible? dem2tin, how do I run it? Like cmd c: dem2tin...whats the code line? 
Best regards, Tobias

**Comment by adrpar** [comment]
Hi @Tobias1234,
thank you for using tin-terrain. It is possible, to compile tin-terrain without the docker installation. In order to do that, just follow the instructions in the section "Building on macOS" or "Building on Linux" under the "Installation" section.

Once you are done with that, you can use tin-terrain as described under the "Usage" section.

If you have any further questions regarding compilation or usage, just let us know.

Best regards,
Adrian
