### ISSUE TITLE
Terrain shadow

### ISSUE THREAD

**Issue by frodrigo** [heremaps/tin-terrain#48]
Unless I'm wrong. The Cesium.SceneMode.SCENE3D is not supported because the normal are not included in the tiles? Do you plan to add normal / allow shadow / SCENE3D?

**Comment by fester** [comment]
Hi @frodrigo,

Indeed, vertex normals computation is not implemented. I will read the format spec and proposed normal encoding algorithm and see how complicated it is to extend the implementation.

**Comment by BTolputt** [comment]
Adding the vertex normals will make this the "go to" Cesium tile processing tool. Currently the only ones that do it are proprietary. As I understand it, the code "should" be relatively simple once the normals are calculated. The format is simply to add a block of vertex normals (same size as the vertex array) at the end with a type value ("1") and the normals compressed by oct-encoding them.

**Comment by fester** [comment]
To give an update, we have a consensus to add normals generation to tin-terrain. However I need to clear some other commitments before giving it a go, ETA is roughly this or next week.

**Comment by BTolputt** [comment]
Sorry to pester, just working out timing details for code I'm working on too - is this still looking for a release this week?

**Comment by delfrrr** [comment]
@BTolputt tin-terrain is experimental tool which we released to explore the landscape and use cases of Surface Data and 3D Maps.

We put this issue on top of the backlog but cannot commit to specific timeline for it.

However it will help us prioritise the issue if you elaborate your use case of using tin-terrain:
What is the industry you are in?
What is your final deliverable you are trying to achieve?

**Comment by BTolputt** [comment]
Is there a way to contact you privately? Whilst not "super secret" by any means, I don't yet have permission from my bosses to share details to the public, but I can talk to you directly about it.

**Comment by BTolputt** [comment]
@delfrrr @fester - has the survey been sent (& I've missed it) or is it still to be done?

**Comment by fester** [comment]
Hey @BTolputt and @frodrigo , thank you for your patience and finally I'm glad to inform you that there is a way to add normals to the terrain. However, there are some shortcomings:
1. I added it and tried to follow spec as close as possible but due to various reasons never checked whether written values make sense. In best case this will happen somewhen next week.
2. There is a well grounded suspiction that surface normals will not be smooth across tile edges, therefore there will be an edge visible. However, because of #1 I could not check it myself.

Because this feature begs for testing, I didn't merge it into master yet but you can check it out from [terrain-normals.fester](https://github.com/heremaps/tin-terrain/tree/terrain-normals.fester) branch. If you have some spare time and a will to help the project, I kindly ask you to give it a go and share whether it works well (i.e. whether the orientation of normals is correct, are there shading problem across tile borders, etc). 

In order to try this feature, you need to check out the aforementioned branch, follow normal build instructions and add '--normals' CLI switch to dem2tintiles subcommand.

**Comment by frodrigo** [comment]
Just starting to look at. I see you have indentation problem in you new code.

**Comment by fester** [comment]
Whoa, my Emacs rebelled against my will. Fixed, thanks for pointing it out.

**Comment by BTolputt** [comment]
@fester - Tried the new code, but cannot tell whether it works or not as I am having the issue referred to [here](https://github.com/heremaps/tin-terrain/issues/51). Once I get that cleared up, I'll report back with details on the normals. Apologies.

**Comment by delfrrr** [comment]
@BTolputt hey! finally put survey together. It would help us if you check it out (it is fully anonymous)
https://survey.research-feedback.com/jfe/form/SV_6qVft7VrQfwsDml

**Comment by BTolputt** [comment]
@delfrrr - thanks mate. Hope my input helps :)

**Comment by frodrigo** [comment]
My test fails. But not sure what wrong, if it's about the top level tiles, bad normals or something else. My tests result in black only.

**Comment by fester** [comment]
Thanks for trying, we will investigate the problem ourselves and try to
find an issue. It will be very helpful for us if you could publish your
code or describe your setup.

**Comment by fester** [comment]
@frodrigo We checked it on our side and it works as expected. Probably you see nothing because Cesium can't handle missing tiles _all_ zoomlevels. You can find more details [in this comment](https://github.com/heremaps/tin-terrain/issues/51#issuecomment-460590228). 

Unfortunately, normals generated with tin-terrain are not smooth because of how we perform tiling and therefore tile borders are visible. Fixing this requires a different approach which I am thinking about now. It's outside this issue and will close it for now.
