### ISSUE TITLE
No layers.json

### ISSUE THREAD

**Issue by BTolputt** [heremaps/tin-terrain#52]
In order for CesiumJS to work, I've found it needs a layers.json file to know what tiles are available, their details, projection, etc. This is not produced by dem2tintiles.

**Comment by fester** [comment]
Have to close this one because layers.json is not a part of quantized mesh spec and therefore it's not in the scope of tin-terrain. This is not even a file, but an endpoint in [Geoserver API spec](https://docs.geoserver.org/latest/en/api/#/latest/en/api/1.0.0/layers.yaml). Paging @delfrrr or @nik-garmash for suggestions on how to use the tiles in Cesium.

**Comment by BTolputt** [comment]
@fester - whilst technically true (it's not a part of the spec), my understanding is that CesiumJS is the only application currently using quantised 3D tiles outside, perhaps, proprietary projects we're not aware of externally.

As loading tiles into CesiumJS is pretty much a necessity to use them (outside afore mentioned proprietary projects), whilst not strictly part of the quantized-mesh spec, it is a de facto requirement for their use surely? Even if only for testing the output.

**Comment by nik-garmash** [comment]
@BTolputt you're not required to have layers.json in order to render terrain with Cesium. You just need to set up [CesiumTerrainProvider](https://cesiumjs.org/refdoc/
https://cesiumjs.org/Cesium/Build/Documentation/CesiumTerrainProvider.html?classFilter=terrain#CesiumTerrainProvider) and pass it as `terrainProvider` to `Cesium.Viewer`.

See [Terrain Tutorial](https://cesium.com/docs/tutorials/terrain/), it has a paragraph at the end about different terrain provider other than World Terrain.
