### ISSUE TITLE
error when running dem2tintiles using example file "dems_10m.dem"

### ISSUE THREAD

**Issue by morishuz** [heremaps/tin-terrain#7]
when using command:
`dem2tintiles --method terra  --max-error 10 --input "/tin-terrain/3rdparty/craterlake/dems_10m.dem"  --output-dir "/tiles"` 
I get the following error:
`ERROR RasterIO.cpp:324 Can not match projection to EPSG:3857`

**Comment by fester** [comment]
This is because the crater lake DEM is not in EPSG:3857. You need to reproject it using something like this: `gdalwarp -t_srs EPSG:3857 dems_10m.dem dems_10m.tif`. In order to correct visual artifacts you can specify resampling algorithm with `-r` argument, please see [the official documentation](https://www.gdal.org/gdalwarp.html).

**Comment by ylian-here** [comment]
I added a section in README about how to use sample datasets. Closing this.
